=== wa491o/mp/annc/target/play/modules/core/conf/module.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://wisorg.com/schema/module" targetNamespace="http://wisorg.com/schema/module"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="module" type="module" />

	<xs:element name="role" type="role" />

	<xs:element name="roles" type="roles" />

	<xs:element name="configurations" type="configurations" />

	<xs:element name="fixtures" type="fixtures" />

	<xs:element name="console" type="console" />

	<xs:element name="menu" type="menu" />

	<xs:element name="item" type="item" />

	<xs:element name="script" type="script" />
	
	<xs:element name="sql" type="xs:string"/>

	<xs:element name="job" type="job" />

	<xs:element name="app" type="app" />

	<xs:element name="config" type="config" />

	<xs:element name="biz" type="biz" />

	<xs:complexType name="module">
		<xs:all minOccurs="0">
			<xs:element ref="roles" minOccurs="0"/>
			<xs:element ref="configurations" minOccurs="0"/>
			<xs:element ref="fixtures" minOccurs="0"/>
			<xs:element ref="console" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="index" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="console">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="menu" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="menu">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element ref="item"/>
				<xs:element ref="menu"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="primary" type="xs:boolean" default="true" />
		<xs:attribute name="index" type="xs:int" />
		<xs:attribute name="icon" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="item">
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="title" type="xs:string" use="required" />
		<xs:attribute name="action" type="xs:string" use="required" />
		<xs:attribute name="index" type="xs:int" />
		<xs:attribute name="check" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="role">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="type" type="roleType" />
	</xs:complexType>

	<xs:complexType name="roles">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="role" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="fixtures">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element ref="script"/>
				<xs:element ref="job"/>
				<xs:element ref="sql"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="script">
		<xs:attribute name="db-type" type="dbType" use="required" />
		<xs:attribute name="file" type="xs:string" use="required" />
		<xs:attribute name="sql-type" type="sqlType" />
	</xs:complexType>
	
	<xs:complexType name="job">
		<xs:attribute name="class" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="configurations">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="app" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="config">
		<xs:attribute name="key" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
		<xs:attribute name="type" type="configType"/>
	</xs:complexType>

	<xs:complexType name="biz">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="config" />
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="app">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="biz" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="appType" use="required" />
	</xs:complexType>

	<xs:simpleType name="appType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="COMMON_SERVICE" />
			<xs:enumeration value="BIZ_MODULE" />
			<xs:enumeration value="THIRD_PARTY" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="roleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BUILD_IN" />
			<xs:enumeration value="END_USER_ROLE" />
			<xs:enumeration value="ADMIN_USER_ROLE" />
			<xs:enumeration value="APPLICATION_ROLE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dbType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="mysql" />
			<xs:enumeration value="oracle" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="sqlType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ddl" />
			<xs:enumeration value="dml" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="configType">
		<xs:annotation>
			<xs:documentation>
				<![CDATA[
				Now,We use only SPACE. Default value is SPACE.
				]]>			
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="FS" />
			<xs:enumeration value="SEARCHER" />
			<xs:enumeration value="OTHER" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== wa491o/mp/annc/target/play/modules/application/conf/module.meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://wisorg.com/schema/module"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://wisorg.com/schema/module http://dev.wisorg.com/pub/module.xsd" title="应用超市">
	<roles>
		<role name="app.list" title="应用管理" type="ADMIN_USER_ROLE"  />
		<role name="app.category" title="应用分类" type="ADMIN_USER_ROLE" />
		<role name="poster.admin" title="超市海报" type="ADMIN_USER_ROLE" />
		<role name="client.admin" title="终端版本" type="ADMIN_USER_ROLE" />
		<role name="app.admin" title="应用管理" type="ADMIN_USER_ROLE" />
		<role name="scope.basic" title="普通应用" type="APPLICATION_ROLE" />
		<role name="scope.pro" title="特权应用" type="APPLICATION_ROLE" />
		<role name="scope.trusted" title="信任应用" type="APPLICATION_ROLE" />
	</roles>
	
	<configurations>
		<app name="移动应用" key="app" type="BIZ_MODULE">
			<biz name="应用-图标" key="app-icon">
				<config key="app-icon" value="{'initCheck':{'height':98,'type':'SIZE','width':98},'accessType':-1,'allowExts':['png'],'bizKey':'app-icon','cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':20480,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'IMAGE','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[{'height':49,'width':49},{'height':74,'width':74},{'height':98,'width':98}]}"/>
			</biz>
			<biz name="应用-安装包" key="app-pkg">
				<config key="app-pkg" value="{'accessType':-1,'allowExts':[],'bizKey':'app-pkg','cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'BIN','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0}"/>
			</biz>
			<biz name="应用截图" key="app-screen">
				<config key="app-screen" value="{'initCheck':{'height':480,'type':'SIZE','width':320},'accessType':-1,'allowExts':['png','jpg'],'bizKey':'app-screen','cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':51200,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'IMAGE','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[]}"/>
			</biz>
			<biz name="应用-公共" key="app-common"/>
		</app>
	</configurations>
	
	<fixtures>
		<script db-type="mysql" file="conf/sql/20131205-01_mysql.sql"/>
		<script db-type="oracle" file="conf/sql/20131205-01_oracle.sql"/>
		<script db-type="oracle" file="conf/sql/20140326_oracle.sql" sql-type="ddl"/>
		<script db-type="mysql" file="conf/sql/20140326_mysql.sql" sql-type="ddl"/>
		<job class="jobs.application.AppFixture" />
	</fixtures>

	<console>
		<menu id="app.main" title="应用超市" primary="true" index="2" icon="icn_app">
			<!-- <item id="app.list" title="应用管理" index="1" action="@{application.AppCtl.appList()}" check="app.admin"/>
			<item id="app.category" title="应用分类" index="2" action="@{application.AppCtl.appCatIndex()}" check="app.admin"/> -->
			<item id="app.list" title="应用管理" index="1" action="@{application.AppCtl.appList()}" check="app.list"/>
			<item id="app.category" title="应用分类" index="2" action="@{application.AppCtl.appCatIndex()}" check="app.category"/>
			<item id="poster.config" title="超市海报" index="4" action="@{poster.PosterCtl.posterList()}" check="poster.admin"/>
			<item id="client.version" title="终端版本" index="10" action="@{version.ClientVersions.index()}" check="client.admin"/>
		</menu>
	</console>
</module>

=== wa491o/mp/annc/target/play/modules/standard/conf/module.meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://wisorg.com/schema/module"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://wisorg.com/schema/module http://dev.wisorg.com/pub/module.xsd" title="标准数据管理" index="1">
	<roles>
		<!-- <role name="standard.admin" title="标准数据管理" type="ADMIN_USER_ROLE" /> -->
	</roles>
	
	<fixtures>
		<script db-type="oracle" file="conf/sql/init_region_oracle.sql" />
		<script db-type="mysql" file="conf/sql/init_region_mysql.sql" />
        
        <script db-type="oracle" file="conf/sql/init_school_oracle.sql" />
        <script db-type="mysql" file="conf/sql/init_school_mysql.sql" />
	</fixtures>

	<console>
		<menu id="system.main">
			
		</menu>
	</console>
</module>

=== wa491o/mp/annc/conf/module.meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://wisorg.com/schema/module"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://wisorg.com/schema/module http://dev.wisorg.com/pub/module.xsd" title="公告管理">
	<roles>
		<!-- <role name="annc.admin" title="公告管理" type="ADMIN_USER_ROLE" /> -->
	</roles>
	
	<fixtures>
		<script db-type="mysql" file="conf/sql/20131211-01_mysql.sql" sql-type="ddl" />
		<script db-type="oracle" file="conf/sql/20140326_oracle.sql" sql-type="ddl" />
		<script db-type="mysql" file="conf/sql/20140326_mysql.sql" sql-type="ddl" />
	</fixtures>

	<console>
		<!-- <menu id="content.main">
			<item id="annc.notice" title="通知公告" index="1" action="@{announcement.AnnouncementCtl.announcementIndex()}" check="annc.admin"/>
		</menu> -->
	</console>
	
	<configurations>
		<app name="通知公告" key="annc" type="BIZ_MODULE">
			<biz name="公告-列表图标" key="annc-icon">
				<config key="annc-icon" value="{'accessType':-1,'allowExts':[],'bizKey':'annc-icon','cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'IMAGE','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[{'height':50,'width':65},{'height':75,'width':98},{'height':100,'width':130}]}"/>
			</biz>
			<biz name="公告-附件" key="annc-attach">
				<config key="annc-attach" value="{'accessType':-1,'allowExts':[],'bizKey':'annc-attach','cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':2048000,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'BIN','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0}"/>
			</biz>
			<biz name="公告-插图" key="annc-inset">
				<config key="annc-inset" value="{'accessType':-1,'allowExts':[],'bizKey':'annc-inset','cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'IMAGE','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[]}"/>
			</biz>
			<biz name="通知公告" key="annc-message"/>
		</app>
	</configurations>
</module>

=== wa491o/mp/annc/target/play/modules/identity/conf/module.meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://wisorg.com/schema/module"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://wisorg.com/schema/module http://dev.wisorg.com/pub/module.xsd" title="用户管理" index="1">
	<roles>
		<role name="identity.account" title="账户管理" type="ADMIN_USER_ROLE" />
		<role name="identity.user" title="用户管理" type="ADMIN_USER_ROLE" />
		<role name="identity.role" title="角色管理" type="ADMIN_USER_ROLE" />
	</roles>

	
	<configurations>
		<app name="身份" key="identity" type="COMMON_SERVICE">
			<biz name="身份-公共" key="identity-common" />
			<biz name="用户-平台" key="scc-user">
				<config key="scc-user" value="{'categories':[], 'coreName':'core0', 'enabled':true, 'fields':[], 'id':'scc-user', 'key':'scc-user', 'name':'用户-平台', 'providerType':'hessian', 'providerUrl':'http://127.0.0.1:9000/service/userIndexProvider', 'tpls':{}, 'vars':{}}" type="SEARCHER"/>
			</biz>
		</app>
		<app name="用户" key="user" type="BIZ_MODULE">
            <biz name="用户-公共" key="user-common" />
			<biz name="用户-头像" key="user-avatar">
				<config key="user-avatar" value="{'accessType':-1,'allowExts':[],'bizKey':'user-avatar','cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'AVATAR','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[{'height':112,'width':112},{'height':168,'width':168},{'height':224,'width':224}]}"/>
			</biz>
		</app>
	</configurations>
	
	<fixtures>
		<script db-type="oracle" file="conf/sql/20140326_oracle.sql" sql-type="ddl"/>
		<script db-type="mysql" file="conf/sql/20140326_mysql.sql" sql-type="ddl"/>
		<job class="jobs.identity.IdentityFixture"/>
		
		<script db-type="oracle" file="conf/sql/account_user_oracle.sql" sql-type="dml"/>
		<script db-type="mysql" file="conf/sql/account_user_mysql.sql" sql-type="dml"/>
		
		<script db-type="oracle" file="conf/sql/cred_value_oracle.sql" sql-type="dml"/>
		<script db-type="mysql" file="conf/sql/cred_value_mysql.sql" sql-type="dml"/>
		
		<script db-type="oracle" file="conf/sql/rename_pwd_back_oracle.sql" sql-type="dml"/>
		<script db-type="mysql" file="conf/sql/rename_pwd_back_mysql.sql" sql-type="dml"/>
		
		<script db-type="oracle" file="conf/sql/ids_no_oracle.sql" sql-type="dml"/>
		<script db-type="mysql" file="conf/sql/ids_no_mysql.sql" sql-type="dml"/>
		
		<script db-type="oracle" file="conf/sql/rename_pwd_back0_oracle.sql" sql-type="dml"/>
		<script db-type="mysql" file="conf/sql/rename_pwd_back0_mysql.sql" sql-type="dml"/>
		
		<script db-type="oracle" file="conf/sql/department_20140929_oracle.sql" sql-type="ddl"/>
        <script db-type="mysql" file="conf/sql/department_20140929_mysql.sql" sql-type="ddl"/>
        
        <script db-type="oracle" file="conf/sql/user_20141016_oracle.sql" sql-type="ddl"/>
        <script db-type="mysql" file="conf/sql/user_20141016_mysql.sql" sql-type="ddl"/>
	</fixtures>

	<console>
		<menu id="identity.user.main" title="用户管理" index="1" primary="true" icon="icn_user">
            <item id="identity.account" title="账户管理" index="1" action="@{identity.UserCtl.accountManage()}" check="identity.account"/>
			<item id="identity.user" title="用户管理" index="2" action="@{identity.UserCtl.initUserIndex()}" check="identity.user"/>
			<item id="identity.role" title="角色管理" index="3" action="@{identity.UserCtl.roleManage()}" check="identity.role"/>
		</menu>
		
		<!-- <menu id="system.main">
            <item id="identity.auth" title="管理员" index="1" action="@{identity.AdminSetCtl.adminManage()}" check="admin.admin"/>
			<item id="identity.group" title="管理员组" index="2" action="@{identity.UserGroupCtl.userGroupIndex()}" check="admin.admin"/>
		</menu> -->
		
		
	</console>
</module>

=== wa491o/mp/annc/target/play/modules/core/conf/module.meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://wisorg.com/schema/module"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://wisorg.com/schema/module http://dev.wisorg.com/pub/module.xsd" title="系统管理" index="0">
	<roles>
		<!-- <role name="core.admin" title="系统管理" type="ADMIN_USER_ROLE" /> -->
		<!-- <role name="identity.auth" title="管理员" type="ADMIN_USER_ROLE" />
		<role name="identity.group" title="管理员组" type="ADMIN_USER_ROLE" /> -->
		
		<role name="domain.admin" title="产品域" type="ADMIN_USER_ROLE" />
		<role name="module.admin" title="模块设置" type="ADMIN_USER_ROLE" />
		<role name="cache.admin" title="缓存设置" type="ADMIN_USER_ROLE" />
		<role name="tables.admin" title="数据结构" type="ADMIN_USER_ROLE" />
		<role name="message.admin.set" title="消息设置" type="ADMIN_USER_ROLE" />
		<role name="imagelist.admin" title="图片列表" type="ADMIN_USER_ROLE" />
		<role name="fs.admin" title="文件管理" type="ADMIN_USER_ROLE" />
		<role name="searcher.admin" title="索引管理" type="ADMIN_USER_ROLE" />
		<role name="tester.admin" title="API工具" type="ADMIN_USER_ROLE" /> 
		
	</roles>
	
	<fixtures>
		<job class="jobs.DomainFixture"/>
		
		<script db-type="oracle" file="conf/sql/count_history_oracle.sql" sql-type="dml"/>
	</fixtures>

	<console>
        
        <menu id="content.main" title="内容管理" primary="true" index="4" icon="icn_content"/>
        
		<menu id="system.main" title="系统管理" index="100" primary="true" icon="icn_set">
            <item id="identity.auth" title="管理员" index="1" action="@{identity.AdminSetCtl.adminManage()}" check="identity.auth"/>
			<item id="identity.group" title="管理员组" index="2" action="@{identity.UserGroupCtl.userGroupIndex()}" check="identity.group"/>
            <item id="domain.config" title="产品域" index="3" action="@{config.DomainCtl.index()}" check="domain.admin"/>
			<item id="core.config" title="模块设置" action="@{config.AppCtl.index()}" check="module.admin"/>
			<item id="cache.config" title="缓存设置" action="@{config.CacheCtl.index()}" check="cache.admin"/>
			<item id="core.tables" title="数据结构" action="@{TableCtl.index()}" check="tables.admin"/>
			<item id="message.sms" title="消息设置" index="6" action="@{message.MessageCtl.smsChannel()}" check="message.admin.set"/>
			<item id="imagelist.config" title="图片列表" index="10" action="@{imagelist.ImageListCtl.categoryList()}" check="imagelist.admin"/>
			<item id="fs.config" index="30" title="文件设置" action="@{fs.CfgCtl.index()}" check="fs.admin"/>	
			<item id="searcher.console" index="50" title="索引管理" action="@{searcher.ConsoleCtl.console()}" check="searcher.admin"/>
			<item id="tester.tool" title="API工具" index="100" action="@{tester.ApiCtl.index()}" check="tester.admin"/>
		</menu>
		
	</console>
	
	<configurations>
		<app name="系统平台" key="sys" type="BIZ_MODULE">
			<biz name="系统-图片" key="image">
				<config key="image" value="{'accessType':-1,'allowExts':[],'cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'initResize':{'height':800,'width':800},'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'IMAGE','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[{'height':10,'width':10},{'height':50,'width':50}]}"/>
			</biz>
			<biz name="系统-文件" key="bin">
				<config key="bin" value="{'accessType':-1,'allowExts':[],'cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'BIN','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0}"/>
			</biz>
			<biz name="系统-视频" key="video">
				<config key="video" value="{'accessType':-1,'allowExts':['mpg', 'mpeg', 'mpe', 'avi', 'mov', 'asf', 'mp4', 'wmv', 'flv', '3gp', 'rm', 'rmvb'],'cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'BIN','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0}"/>
			</biz>
			<biz name="系统-压缩文件" key="zip">
				<config key="zip" value="{'accessType':-1,'allowExts':[],'cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'ZIP','unzip':true,'urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[]}"/>
			</biz>
			<biz name="系统-系统消息" key="sys-message">
				<config key="sys-message" value="{'accessType':-1,'allowExts':[],'cacheSeconds':0,'defaultIds':[1,2],'extractMetadata':false,'maxSize':-1,'quota':-1,'readScope':'ALL','status':'ENABLED','timeout':10,'type':'IMAGE','urlRewrite':false,'used':0,'userQuita':-1,'writeScope':'ALL','xsendfileLimitRate':0,'zooms':[]}"/>
			</biz>
		</app>
		<app name="域" key="domain" type="BIZ_MODULE"/>
	</configurations>
</module>
